#!/system/bin/sh
#Script originally made by Axetilen. Modified by Sultan (android1234567)
#Updated for albinoman887's ChronicKernel (98% of the credit goes to android1234567. Thanks so much man :)
#Updated for ChroncBruce-v2-linaro

# Configure your options here #


# Config 3D GPU clock
# 228571000 = 228mhz
# 266667000 = 267mhz (default)
# 300000000 = 300mhz (Recomended For balance of Performance and Battery life)
# 320000000 = 320mhz
GPU=266667000;


# Config 2D GPU clock
# 145455000 = 145mhz
# 160000000 = 160mhz
# 200000000 = 200mhz (default)
# 228571000 = 228mhz (Recomended For balance of Performance and Battery life)
# 266667000 = 267mhz
DD=200000000;


# Badass
# possible values
# 1 = performance
# 2 = balanced
# 3 = battery saving
BADASS=2


# Enable Sweep2Wake
# 0 = disabled (default)
# 1 = enabled
# 2 = enabled (with no button backlight)
SWEEP=0


# Enable Fastcharge
# 0 = disabled
# 1 = substitute AC to USB charging always
# 2 = substitute AC to USB charging only if there is no USB peripheral detected
FASTCHARGE=0;


# Fsync Control
# Disabled by default (recomended)
# 2 = Fsync disabled
# 1 = Fsync enabled
FSYNC=2;


# End of configurable options #


################# DON'T CHANGE ANYTHING BELOW THIS LINE #################



# Config 3D GPU setting
    chmod 644 /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    echo $GPU > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk
    echo $GPU > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/gpuclk


# Config 2D GPU setting
    chmod 644 /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk
    chmod 644 /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/gpuclk
    chmod 644 /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/max_gpuclk
    chmod 644 /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/gpuclk
    echo $DD > /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/max_gpuclk
    echo $DD > /sys/devices/platform/kgsl-2d0.0/kgsl/kgsl-2d0/gpuclk
    echo $DD > /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/max_gpuclk
    echo $DD > /sys/devices/platform/kgsl-2d1.1/kgsl/kgsl-2d1/gpuclk
 

# Config USB forced fastcharge
    chmod 644 /sys/kernel/fast_charge/force_fast_charge
    echo "$FASTCHARGE" > /sys/kernel/fast_charge/force_fast_charge


# Config Sweep2Wake (with compatibility with NLJ's fix)
    chmod 644 /sys/android_touch/sweep2wake
    echo "$SWEEP" > /sys/android_touch/sweep2wake
	if [ "$SWEEP" = "0" ]
	then
    		chmod 644 /sys/android_touch/sweep2wake
   		echo 0 > /sys/android_touch/sweep2wake
	fi

	if [ "$SWEEP" = "1" ]
	then
    		chmod 666 /sys/android_touch/sweep2wake
   		echo 1 > /sys/android_touch/sweep2wake
	fi

	if [ "$SWEEP" = "2" ]
	then
    		chmod 666 /sys/android_touch/sweep2wake
   		echo 2 > /sys/android_touch/sweep2wake
	fi


# Config badass CPU Gonvernor
CUR_GOV="`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`"
echo badass > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
sleep 3
case ${BADASS} in
	1)
		$L "badass: setting performance oriented configuration"
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1512000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
		echo 120 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 80 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 8 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 4 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
	;;
	2)
		$L "badass: setting balanced configuration"
		echo 918000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
                echo 50000 > /sys/devices/system/cpu/cpufreq/badass/sampling_rate
		echo 130 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 100 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 14 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 6 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
	;;
	3)
		$L "badass: setting battery saving configuration"
		echo 918000 > /sys/devices/system/cpu/cpufreq/badass/two_phase_freq;
		echo 1188000 > /sys/devices/system/cpu/cpufreq/badass/three_phase_freq;
		echo 140 > /sys/devices/system/cpu/cpufreq/badass/busy_threshold;
		echo 110 > /sys/devices/system/cpu/cpufreq/badass/busy_clr_threshold;
		echo 80 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_threshold;
		echo 20 > /sys/devices/system/cpu/cpufreq/badass/semi_busy_clr_threshold;
	;;
esac
echo ${CUR_GOV} > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor


# Set min freq to 384mhtz as 192 is buggy and don't want complaints about soft reboots :)
    chmod 644 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
    echo 384000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq


# Config Fsync
if [ "$FSYNC" = "2" ]
then
    echo "0" > sys/class/misc/fsynccontrol/fsync_enabled
fi
